version: 2.1

executors:
  ipinfo_env:
    docker:
      - image: circleci/python
    working_directory: ~/workspace

jobs:
  build:
    executor: ipinfo_env
    steps:
      - checkout
      - run:
          name: Install Python module
          command: |
            sudo pip install ipwhois
            sudo pip install flask
      - run: 
          name: run app
          command: sudo python flaskapp.py &
 # test:
    
workflow:
  version: 2.1
  build_test:
    jobs:
      - build
#      - test:
#        requires:
#          - build