version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - run:
          command: |
            sudo pip install ipwhois
            sudo pip install flask
      - checkout

      - run: echo "hello world"