version: 2.1

executors:
  ipinfo_env:
    docker:
      - image: circleci/python
    working_directory: ~/workspace

jobs:
  build:
    executor: ipinfo_env
    steps:
      - checkout
      - run:
        name: Install Python modules
        command: 
          sudo pip install ipwhois flask

  test:
    executor: ipinfo_env
    steps:
      - run: sudopython flaskapp.py

workflow:
  version: 2.1
  build_test:
    jobs:
      - build
      - test:
        requires:
          - build