version: 2.1

executors:
  ipinfo_env:
    docker:
      - image: circleci/python
    working_directory: ~/workspace

jobs:
  build:
    docker:
      - image: circleci/python
    working_directory: ~/workspace
    steps:
      - checkout
