version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - run:
          command: |
            pip install flask
            pip install ipwhois
            pip install json
            pip install requests
      - checkout

      - run: echo "hello world"