version: 2.1

#executors:
#  ipinfo_env:
#    docker:
#      - image: circleci/python
#    working_directory: ~/workspace

jobs:
  build:
    docker:
      - image: circleci/python
    working_directory: ~/workspace
    steps:
      - checkout

      - run:
        name: Install Python modules
        command: |
          sudo pip install ipwhois
          sudo pip install flask
      - run: sudo python flaskapp.py

#workflow:
#  version: 2.1
#  build_test:
#    jobs:
#      - build
#      - test:
#        requires:
#          - build