version: 2.1

executors:
  ipinfo_env:
    docker:
      - image: circleci/python
    working_directory: ~/workspace
  ec2:
    machine:
      image: circleci/classic:edge
    working_directory: ~/ipinfo
    
jobs:
  build:
    executor: ipinfo_env
    steps:
      - checkout
      - run:
          name: Install Python module
          command: |
            sudo pip install ipwhois
            sudo pip install flask
      - run: 
          name: run app
          command: sudo python flaskapp.py &
  deploy:
    executor: ec2
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "07:f3:04:c5:41:09:50:a9:e7:19:7a:1a:f3:51:23:99"

      - run: ssh ${USER_NAME}@${HOST_NAME} 'git pull && sudo systemctl restart ipinfo'

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build