version: 2.1

executors:
  ipinfo_env:
    docker:
      - image: circleci/python

jobs:
  build:
    working_directory: ~/workspace
    executor: ipinfo_env
    steps:
      - run:
        name: Install Python modules
        command: |
          sudo pip install ipwhois
          sudo pip install flask
      - checkout
  test:
    working_directory: ~/workspace
    executor: ipinfo_env
    steps:
      - run: python flaskapp.py
        requires:

workflow:
  version: 2.1
  build_test:
    jobs:
      - build
      - test
        requires;
          - build